name=SafeSerial
version=1.0.3
author=Péter Soós
maintainer=Péter Soós
sentence=Asynchronous, Thread-safe, and Non-blocking Serial Library for ESP32 Arduino Core (with HWCDC and USBCDC support).
paragraph=SafeSerial uses a FreeRTOS background task and a queue to handle serial output without blocking your main application code. Additionally it try to solve the common S3 issue where Native USB CDC logging stalls during high WiFi or CPU load.
keywords=logging, serial, async, esp32, esp32-s3, usb-cdc, freertos
category=Communication
url=https://github.com/soosp/SafeSerial.git
architectures=esp32